PulsarStore.Language:Language("de", 1)
    :Plural("argument")("Argument")("Argumente")()
    :Plural("credit")("Kredit")("Kredite")()
    :Plural("item")("Gegenstand")("Gegenstände")()

    -- Generisch
    :Set("brand", "Pulsar Store")
    :Set("admin", "Admin")
    :Set("yes", "Ja")
    :Set("no", "Nein")
    :Set("unknown", "Unbekannt")
    :Set("alreadyown", "Du besitzt diesen Gegenstand bereits.")
    :Set("owned", "Im Besitz")
    :Set("permanent", "Permanent")
    :Set("cancel", "Abbrechen")
    :Set("purchase", "Kaufen")
    :Set("buy", "Kaufen")
    :Set("sell", "Verkaufen")
    :Set("credit", "{{plural:credit|creditsCount}}")
    :Set("credits", "Kredite")
    :Set("money", "Geld")
    :Set("close", "Schließen")
    :Set("return", "Zurück")
    :Set("enable", "Aktivieren")
    :Set("enabled", "Aktiviert")
    :Set("disable", "Deaktivieren")
    :Set("disabled", "Deaktiviert")
    :Set("item", "{{plural:item|count}}")

    -- Fehler
    :Set("error.permissions", "Unzureichende Berechtigungen")
    :Set("error.permissions.message", "Du hast keine Berechtigung, das zu tun.")
    :Set("error.ratelimit", "Du sendest zu viele Anfragen. Bitte warte einige Sekunden und versuche es erneut.")

    -- Hauptmenü
    :Set("mainmenu.home", "Startseite")
    :Set("mainmenu.inventory", "Inventar")
    :Set("mainmenu.credits.buymore", "Mehr Kredite kaufen")
    :Set("search", "Suche...")
    :Set("search.hidepurchased", "Gekaufte ausblenden")

    -- Gegenstände
    :Set("item.discountprice", "{{oldprice}} {{newprice}} {{plural:credit|creditsCount}}")
    :Set("item.percentoff", "{{percent}}% Rabatt!")
    :Set("item.whatsincluded", "Enthält:")
    :Set("item.bundle.creditstext", "{{credits}} - Bundle")
    :Set("item.price", "{{price}} {{plural:credit|creditsCount}}")

    -- Kategorien
    :Set("admin.categories", "Kategorien")
    :Set("admin.categories.create", "Kategorie erstellen")
    :Set("admin.categories.create.name", "Name")
    :Set("admin.categories.create.name.placeholder", "Meine Kategorie")
    :Set("admin.categories.create.icon", "Icon")
    :Set("admin.categories.create.create", "Erstellen")
    :Set("admin.categories.create.noname", "Name darf nicht leer sein")
    :Set("admin.categories.create.noicon", "Icon darf nicht leer sein")
    :Set("admin.categories.create.success", "Kategorie erfolgreich erstellt!")
    :Set("admin.categories.create.failed", "Fehler beim Erstellen der Kategorie: {{err}}")
    :Set("admin.categories.edit", "Kategorie bearbeiten")
    :Set("admin.categories.edit.edit", "Bearbeiten")
    :Set("admin.categories.edit.noname", "Name darf nicht leer sein")
    :Set("admin.categories.edit.noicon", "Icon darf nicht leer sein")
    :Set("admin.categories.edit.success", "Kategorie erfolgreich bearbeitet!")
    :Set("admin.categories.edit.failed", "Fehler beim Bearbeiten der Kategorie: {{err}}")
    :Set("admin.categories.delete", "Kategorie löschen")
    :Set("admin.categories.delete.success", "Kategorie erfolgreich gelöscht!")
    :Set("admin.categories.delete.failed", "Fehler beim Löschen der Kategorie: {{err}}")
    :Set("admin.categories.delete.confirm", "Bist du sicher, dass du diese Kategorie löschen möchtest?")

    -- Pakete
    :Set("admin.packages", "Pakete")
    :Set("admin.packages.create", "Paket erstellen")
    :Set("admin.packages.create.name", "Name")
    :Set("admin.packages.create.name.placeholder", "Mein Paket")
    :Set("admin.packages.create.price", "Preis")
    :Set("admin.packages.create.currency", "Währung")
    :Set("admin.packages.create.permanent", "Ist permanent?")
    :Set("admin.packages.create.icon", "Icon")
    :Set("admin.packages.create.category", "Kategorie")
    :Set("admin.packages.create.next", "Weiter")
    :Set("admin.packages.create.actions", "Neue Paket-Aktion")
    :Set("admin.packages.create.actions.argument", "{{plural:argument|count}}")
    :Set("admin.packages.create.create", "Erstellen")
    :Set("admin.packages.edit", "Paket bearbeiten")
    :Set("admin.packages.edit.edit", "Bearbeiten")
    :Set("admin.packages.edit.delete", "Löschen")
    :Set("admin.packages.create.success", "Paket erfolgreich erstellt!")
    :Set("admin.packages.create.failed", "Fehler beim Erstellen des Pakets.")
    :Set("admin.packages.edit.success", "Paket erfolgreich bearbeitet!")
    :Set("admin.packages.edit.failed", "Fehler beim Bearbeiten des Pakets.")
    :Set("admin.packages.delete.success", "Paket erfolgreich gelöscht!")
    :Set("admin.packages.delete.failed", "Fehler beim Löschen des Pakets.")

    -- Bundles
    :Set("admin.bundles", "Bundles")
    :Set("admin.bundles.create", "Bundle erstellen")
    :Set("admin.bundles.create.name", "Name")
    :Set("admin.bundles.create.name.placeholder", "Mein Bundle")
    :Set("admin.bundles.create.price", "Preis")
    :Set("admin.bundles.create.currency", "Währung")
    :Set("admin.bundles.create.icon", "Icon")
    :Set("admin.bundles.create.category", "Kategorie")
    :Set("admin.bundles.create.next", "Weiter")
    :Set("admin.bundles.create.bundlepackage", "Neues Bundle-Paket")
    :Set("admin.bundles.create.create", "Erstellen")
    :Set("admin.bundles.edit", "Bundle bearbeiten")
    :Set("admin.bundles.edit.edit", "Bearbeiten")
    :Set("admin.bundles.edit.delete", "Löschen")
    :Set("admin.bundles.create.success", "Bundle erfolgreich erstellt!")
    :Set("admin.bundles.create.failed", "Fehler beim Erstellen des Bundles.")
    :Set("admin.bundles.edit.success", "Bundle erfolgreich bearbeitet!")
    :Set("admin.bundles.edit.failed", "Fehler beim Bearbeiten des Bundles.")

    -- Rabatte
    :Set("percentoff", "{{percent}}% Rabatt!")
    :Set("discount", "Rabatt")
    :Set("admin.discounts", "Rabatte")
    :Set("admin.discounts.delete", "Rabatt löschen")
    :Set("admin.discounts.delete.confirm", "Bist du sicher, dass du diesen Rabatt löschen möchtest?")
    :Set("admin.discounts.create", "Rabatt erstellen")
    :Set("admin.discounts.create.amount", "Betrag")
    :Set("admin.discounts.create.enddate", "Enddatum")
    :Set("admin.discounts.create.failed", "Fehler beim Erstellen des Rabatts.")
    :Set("admin.discounts.create.success", "Rabatt erfolgreich erstellt!")
    :Set("admin.discounts.items", "Rabatt-Gegenstände")
    :Set("admin.discounts.save", "Speichern")
    :Set("admin.discounts.items.add", "Gegenstand hinzufügen")
    :Set("admin.discounts.items.add.success", "Gegenstand erfolgreich hinzugefügt!")
    :Set("admin.discounts.items.add.failed", "Fehler beim Hinzufügen des Gegenstands.")
    :Set("admin.discounts.items.remove.success", "Gegenstand erfolgreich entfernt!")
    :Set("admin.discounts.items.remove.failed", "Fehler beim Entfernen des Gegenstands.")

    -- Benutzer
    :Set("admin.users", "Benutzer")
    :Set("admin.users.remove", "Entfernen")
    :Set("admin.users.remove.success", "Kauf erfolgreich entfernt!")
    :Set("admin.users.add.success", "Kauf erfolgreich hinzugefügt!")

    :Set("admin.home", "Zurück zur Startseite")

    -- Sonstiges
    :Set("periodic", "Du hast {{creditsCount}} {{plural:credit|creditsCount}} als Belohnung für das Spielen auf dem Server erhalten!")
:Register()
