PulsarStore.Language:Language("es", 1)
    :Plural("argument")("Argumento")("Argumentos")()
    :Plural("credit")("Crédito")("Créditos")()
    :Plural("item")("Ítem")("Ítems")()

    -- Genérico
    :Set("brand", "Tienda Pulsar")
    :Set("admin", "Admin")
    :Set("yes", "Sí")
    :Set("no", "No")
    :Set("unknown", "Desconocido")
    :Set("alreadyown", "Ya tienes este ítem.")
    :Set("owned", "Adquirido")
    :Set("permanent", "Permanente")
    :Set("cancel", "Cancelar")
    :Set("purchase", "Comprar")
    :Set("buy", "Comprar")
    :Set("sell", "Vender")
    :Set("credit", "{{plural:credit|creditsCount}}")
    :Set("credits", "Créditos")
    :Set("money", "Dinero")
    :Set("close", "Cerrar")
    :Set("return", "Regresar")
    :Set("enable", "Activar")
    :Set("enabled", "Activado")
    :Set("disable", "Desactivar")
    :Set("disabled", "Desactivado")
    :Set("item", "{{plural:item|count}}")

    -- Errores
    :Set("error.permissions", "Permisos Insuficientes")
    :Set("error.permissions.message", "No tienes permiso para hacer eso.")
    :Set("error.ratelimit", "Estás enviando demasiadas solicitudes. Por favor, espera unos segundos e inténtalo de nuevo.")

    -- Menú Principal
    :Set("mainmenu.home", "Inicio")
    :Set("mainmenu.inventory", "Inventario")
    :Set("mainmenu.credits.buymore", "Comprar más créditos")
    :Set("search", "Buscar...")
    :Set("search.hidepurchased", "Ocultar Comprados")

    -- Ítems
    :Set("item.discountprice", "{{oldprice}} {{newprice}} {{plural:credit|creditsCount}}")
    :Set("item.percentoff", "{{percent}}% de descuento!")
    :Set("item.whatsincluded", "Incluye:")
    :Set("item.bundle.creditstext", "{{credits}} - Paquete")
    :Set("item.price", "{{price}} {{plural:credit|creditsCount}}")

    -- Categorías
    :Set("admin.categories", "Categorías")
    :Set("admin.categories.create", "Crear Categoría")
    :Set("admin.categories.create.name", "Nombre")
    :Set("admin.categories.create.name.placeholder", "Mi Categoría")
    :Set("admin.categories.create.icon", "Ícono")
    :Set("admin.categories.create.color", "Color")
    :Set("admin.categories.create.create", "Crear")
    :Set("admin.categories.create.noname", "El nombre no puede estar vacío")
    :Set("admin.categories.create.noicon", "El ícono no puede estar vacío")
    :Set("admin.categories.create.success", "¡Categoría creada exitosamente!")
    :Set("admin.categories.create.failed", "Error al crear la categoría: {{err}}")
    :Set("admin.categories.edit", "Editar Categoría")
    :Set("admin.categories.edit.edit", "Editar")
    :Set("admin.categories.edit.noname", "El nombre no puede estar vacío")
    :Set("admin.categories.edit.noicon", "El ícono no puede estar vacío")
    :Set("admin.categories.edit.success", "¡Categoría editada exitosamente!")
    :Set("admin.categories.edit.failed", "Error al editar la categoría: {{err}}")
    :Set("admin.categories.delete", "Eliminar Categoría")
    :Set("admin.categories.delete.success", "¡Categoría eliminada exitosamente!")
    :Set("admin.categories.delete.failed", "Error al eliminar la categoría: {{err}}")
    :Set("admin.categories.delete.confirm", "¿Estás seguro de que deseas eliminar esta categoría?")

    -- Paquetes
    :Set("admin.packages", "Paquetes")
    :Set("admin.packages.create", "Crear Paquete")
    :Set("admin.packages.create.name", "Nombre")
    :Set("admin.packages.create.name.placeholder", "Mi Paquete")
    :Set("admin.packages.create.price", "Precio")
    :Set("admin.packages.create.currency", "Moneda")
    :Set("admin.packages.create.permanent", "¿Es Permanente?")
    :Set("admin.packages.create.icon", "Ícono")
    :Set("admin.packages.create.category", "Categoría")
    :Set("admin.packages.create.color", "Color")
    :Set("admin.packages.create.next", "Siguiente")
    :Set("admin.packages.create.actions", "Nueva Acción del Paquete")
    :Set("admin.packages.create.actions.argument", "{{plural:argument|count}}")
    :Set("admin.packages.create.create", "Crear")
    :Set("admin.packages.edit", "Editar Paquete")
    :Set("admin.packages.edit.edit", "Editar")
    :Set("admin.packages.edit.delete", "Eliminar")
    :Set("admin.packages.create.success", "¡Paquete creado exitosamente!")
    :Set("admin.packages.create.failed", "Error al crear el paquete.")
    :Set("admin.packages.edit.success", "¡Paquete editado exitosamente!")
    :Set("admin.packages.edit.failed", "Error al editar el paquete.")
    :Set("admin.packages.delete.success", "¡Paquete eliminado exitosamente!")
    :Set("admin.packages.delete.failed", "Error al eliminar el paquete.")

    -- Paquetes
    :Set("admin.bundles", "Paquetes")
    :Set("admin.bundles.create", "Crear Paquete")
    :Set("admin.bundles.create.name", "Nombre")
    :Set("admin.bundles.create.name.placeholder", "Mi Paquete")
    :Set("admin.bundles.create.price", "Precio")
    :Set("admin.bundles.create.currency", "Moneda")
    :Set("admin.bundles.create.icon", "Ícono")
    :Set("admin.bundles.create.category", "Categoría")
    :Set("admin.packages.create.color", "Color")
    :Set("admin.bundles.create.next", "Siguiente")
    :Set("admin.bundles.create.bundlepackage", "Nuevo Paquete del Paquete")
    :Set("admin.bundles.create.create", "Crear")
    :Set("admin.bundles.edit", "Editar Paquete")
    :Set("admin.bundles.edit.edit", "Editar")
    :Set("admin.bundles.edit.delete", "Eliminar")
    :Set("admin.bundles.create.success", "¡Paquete creado exitosamente!")
    :Set("admin.bundles.create.failed", "Error al crear el paquete.")
    :Set("admin.bundles.edit.success", "¡Paquete editado exitosamente!")
    :Set("admin.bundles.edit.failed", "Error al editar el paquete.")

    -- Descuentos
    :Set("percentoff", "{{percent}}% de descuento!")
    :Set("discount", "Descuento")
    :Set("admin.discounts", "Descuentos")
    :Set("admin.discounts.delete", "Eliminar Descuento")
    :Set("admin.discounts.delete.confirm", "¿Estás seguro de que deseas eliminar este descuento?")
    :Set("admin.discounts.create", "Crear Descuento")
    :Set("admin.discounts.create.amount", "Cantidad")
    :Set("admin.discounts.create.enddate", "Fecha de Finalización")
    :Set("admin.discounts.create.failed", "Error al crear el descuento.")
    :Set("admin.discounts.create.success", "¡Descuento creado exitosamente!")
    :Set("admin.discounts.items", "Ítems de Descuento")
    :Set("admin.discounts.save", "Guardar")
    :Set("admin.discounts.items.add", "Agregar Ítem")
    :Set("admin.discounts.items.add.success", "Ítem agregado exitosamente!")
    :Set("admin.discounts.items.add.failed", "Error al agregar el ítem.")
    :Set("admin.discounts.items.remove.success", "Ítem eliminado exitosamente!")
    :Set("admin.discounts.items.remove.failed", "Error al eliminar el ítem.")

    -- Usuarios
    :Set("admin.users", "Usuarios")
    :Set("admin.users.remove", "Eliminar")
    :Set("admin.users.remove.success", "¡Compra eliminada exitosamente!")
    :Set("admin.users.add.success", "¡Compra agregada exitosamente!")

    :Set("admin.home", "Regresar al Inicio")

    -- Otros
    :Set("periodic", "¡Has sido recompensado con {{creditsCount}} {{plural:credit|creditsCount}} por jugar en el servidor!")
:Register()
