PulsarStore.Language:Language("en", 1)
    :Plural("argument")("Argument")("Arguments")()
    :Plural("credit")("Credit")("Credits")()
    :Plural("item")("Item")("Items")()

    -- Generic
    :Set("brand", "Pulsar Store")
    :Set("admin", "Admin")
    :Set("yes", "Yes")
    :Set("no", "No")
    :Set("unknown", "Unknown")
    :Set("alreadyown", "You already own this item.")
    :Set("owned", "Owned")
    :Set("permanent", "Permanent")
    :Set("cancel", "Cancel")
    :Set("purchase", "Purchase")
    :Set("buy", "Buy")
    :Set("sell", "Sell")
    :Set("credit", "{{plural:credit|creditsCount}}")
    :Set("credits", "Credits")
    :Set("money", "Money")
    :Set("close", "Close")
    :Set("return", "Return")
    :Set("enable", "Enable")
    :Set("enabled", "Enabled")
    :Set("disable", "Disable")
    :Set("disabled", "Disabled")
    :Set("item", "{{plural:item|count}}")

    -- Errors
    :Set("error.permissions", "Insufficient Permissions")
    :Set("error.permissions.message", "You do not have permission to do that.")
    :Set("error.ratelimit", "You are sending too many requests. Please wait a few seconds and try again.")

    -- Main Menu
    :Set("mainmenu.home", "Home")
    :Set("mainmenu.inventory", "Inventory")
    :Set("mainmenu.credits.buymore", "Buy more credits")
    :Set("search", "Search...")
    :Set("search.hidepurchased", "Hide Purchased")

    -- Items
    :Set("item.discountprice", "{{oldprice}} {{newprice}} {{plural:credit|creditsCount}}")
    :Set("item.percentoff", "{{percent}}% off!")
    :Set("item.whatsincluded", "What's included:")
    :Set("item.bundle.creditstext", "{{credits}} - Bundle")
    :Set("item.price", "{{price}} {{plural:credit|creditsCount}}")

    -- Categories
    :Set("admin.categories", "Categories")
    :Set("admin.categories.create", "Create Category")
    :Set("admin.categories.create.name", "Name")
    :Set("admin.categories.create.name.placeholder", "My Category")
    :Set("admin.categories.create.icon", "Icon")
    :Set("admin.categories.create.create", "Create")
    :Set("admin.categories.create.noname", "Name cannot be empty")
    :Set("admin.categories.create.noicon", "Icon cannot be empty")
    :Set("admin.categories.create.success", "Category created successfully!")
    :Set("admin.categories.create.failed", "Failed to create category: {{err}}")
    :Set("admin.categories.edit", "Edit Category")
    :Set("admin.categories.edit.edit", "Edit")
    :Set("admin.categories.edit.noname", "Name cannot be empty")
    :Set("admin.categories.edit.noicon", "Icon cannot be empty")
    :Set("admin.categories.edit.success", "Category edited successfully!")
    :Set("admin.categories.edit.failed", "Failed to edit category: {{err}}")
    :Set("admin.categories.delete", "Delete Category")
    :Set("admin.categories.delete.success", "Category deleted successfully!")
    :Set("admin.categories.delete.failed", "Failed to delete category: {{err}}")
    :Set("admin.categories.delete.confirm", "Are you sure you want to delete this category?")

    -- Packages
    :Set("admin.packages", "Packages")
    :Set("admin.packages.create", "Create Package")
    :Set("admin.packages.create.name", "Name")
    :Set("admin.packages.create.name.placeholder", "My Package")
    :Set("admin.packages.create.price", "Price")
    :Set("admin.packages.create.currency", "Currency")
    :Set("admin.packages.create.permanent", "Is Permanent?")
    :Set("admin.packages.create.icon", "Icon")
    :Set("admin.packages.create.category", "Category")
    :Set("admin.packages.create.next", "Next")
    :Set("admin.packages.create.actions", "New Package Action")
    :Set("admin.packages.create.actions.argument", "{{plural:argument|count}}")
    :Set("admin.packages.create.create", "Create")
    :Set("admin.packages.edit", "Edit Package")
    :Set("admin.packages.edit.edit", "Edit")
    :Set("admin.packages.edit.delete", "Delete")
    :Set("admin.packages.create.success", "Package created successfully!")
    :Set("admin.packages.create.failed", "Failed to create package.")
    :Set("admin.packages.edit.success", "Package edited successfully!")
    :Set("admin.packages.edit.failed", "Failed to edit package.")
    :Set("admin.packages.delete.success", "Package deleted successfully!")
    :Set("admin.packages.delete.failed", "Failed to delete package.")

    -- Bundles
    :Set("admin.bundles", "Bundles")
    :Set("admin.bundles.create", "Create Bundle")
    :Set("admin.bundles.create.name", "Name")
    :Set("admin.bundles.create.name.placeholder", "My Bundle")
    :Set("admin.bundles.create.price", "Price")
    :Set("admin.bundles.create.currency", "Currency")
    :Set("admin.bundles.create.icon", "Icon")
    :Set("admin.bundles.create.category", "Category")
    :Set("admin.bundles.create.next", "Next")
    :Set("admin.bundles.create.bundlepackage", "New Bundle Package")
    :Set("admin.bundles.create.create", "Create")
    :Set("admin.bundles.edit", "Edit Bundle")
    :Set("admin.bundles.edit.edit", "Edit")
    :Set("admin.bundles.edit.delete", "Delete")
    :Set("admin.bundles.create.success", "Bundle created successfully!")
    :Set("admin.bundles.create.failed", "Failed to create bundle.")
    :Set("admin.bundles.edit.success", "Bundle edited successfully!")
    :Set("admin.bundles.edit.failed", "Failed to edit bundle.")

    -- Discounts
    :Set("percentoff", "{{percent}}% off!")
    :Set("discount", "Discount")
    :Set("admin.discounts", "Discounts")
    :Set("admin.discounts.delete", "Delete Discount")
    :Set("admin.discounts.delete.confirm", "Are you sure you want to delete this discount?")
    :Set("admin.discounts.create", "Create Discount")
    :Set("admin.discounts.create.amount", "Amount")
    :Set("admin.discounts.create.enddate", "End Date")
    :Set("admin.discounts.create.failed", "Failed to create discount.")
    :Set("admin.discounts.create.success", "Discount created successfully!")
    :Set("admin.discounts.items", "Discount Items")
    :Set("admin.discounts.save", "Save")
    :Set("admin.discounts.items.add", "Add Item")
    :Set("admin.discounts.items.add.success", "Item added successfully!")
    :Set("admin.discounts.items.add.failed", "Failed to add item.")
    :Set("admin.discounts.items.remove.success", "Item removed successfully!")
    :Set("admin.discounts.items.remove.failed", "Failed to remove item.")

    -- Users
    :Set("admin.users", "Users")
    :Set("admin.users.remove", "Remove")
    :Set("admin.users.remove.success", "Successfully removed purchase!")
    :Set("admin.users.add.success", "Successfully added purchase!")

    :Set("admin.home", "Back Home")

    -- Other
    :Set("periodic", "You have been rewarded {{creditsCount}} {{plural:credit|creditsCount}} for playing on the server!")
:Register()
