PulsarStore.Language:Language("fr", 2)
  :Plural("argument")("Argument")("Arguments")()
  :Plural("credit")("Crédit")("Crédits")()
  :Plural("item")("Objet")("Objets")()
  
  -- Générique
  :Set("brand", "Pulsar Store")
  :Set("admin", "Admin")
  :Set("yes", "Oui")
  :Set("no", "Non")
  :Set("unknown", "Inconnu")
  :Set("alreadyown", "Vous possédez déjà cet objet.")
  :Set("owned", "Possédé")
  :Set("permanent", "Permanent")
  :Set("cancel", "Annuler")
  :Set("purchase", "Acheter")
  :Set("buy", "Acheter")
  :Set("sell", "Vendre")
  :Set("credit", "{{plural:credit|creditsCount}}")
  :Set("credits", "Crédits")
  :Set("money", "Argent")
  :Set("close", "Fermer")
  :Set("return", "Retour")
  :Set("enable", "Activer")
  :Set("enabled", "Activé")
  :Set("disable", "Désactiver")
  :Set("disabled", "Désactivé")
  :Set("item", "{{plural:item|count}}")
  
  -- Erreurs
  :Set("error.permissions", "Permissions insuffisantes")
  :Set("error.permissions.message", "Vous n'avez pas la permission de faire cela.")
  :Set("error.ratelimit", "Vous envoyez trop de requêtes. Veuillez patienter quelques secondes et réessayer.")
  
  -- Menu principal
  :Set("mainmenu.home", "Accueil")
  :Set("mainmenu.inventory", "Inventaire")
  :Set("mainmenu.credits.buymore", "Acheter plus de crédits")
  :Set("search", "Rechercher...")
  :Set("search.hidepurchased", "Masquer les achats")
  
  -- Objets
  :Set("item.discountprice", "{{oldprice}} {{newprice}} {{plural:credit|creditsCount}}")
  :Set("item.percentoff", "{{percent}} % de réduction !")
  :Set("item.whatsincluded", "Inclus :")
  :Set("item.bundle.creditstext", "{{credits}} - Pack")
  :Set("item.price", "{{price}} {{plural:credit|creditsCount}}")
  
  -- Catégories
  :Set("admin.categories", "Catégories")
  :Set("admin.categories.create", "Créer une catégorie")
  :Set("admin.categories.create.name", "Nom")
  :Set("admin.categories.create.name.placeholder", "Ma catégorie")
  :Set("admin.categories.create.icon", "Icône")
  :Set("admin.categories.create.color", "Couleur")
  :Set("admin.categories.create.create", "Créer")
  :Set("admin.categories.create.noname", "Le nom ne peut pas être vide")
  :Set("admin.categories.create.noicon", "L'icône ne peut pas être vide")
  :Set("admin.categories.create.success", "Catégorie créée avec succès !")
  :Set("admin.categories.create.failed", "Échec de la création de la catégorie : {{err}}")
  :Set("admin.categories.edit", "Modifier la catégorie")
  :Set("admin.categories.edit.edit", "Modifier")
  :Set("admin.categories.edit.noname", "Le nom ne peut pas être vide")
  :Set("admin.categories.edit.noicon", "L'icône ne peut pas être vide")
  :Set("admin.categories.edit.success", "Catégorie modifiée avec succès !")
  :Set("admin.categories.edit.failed", "Échec de la modification de la catégorie : {{err}}")
  :Set("admin.categories.delete", "Supprimer la catégorie")
  :Set("admin.categories.delete.success", "Catégorie supprimée avec succès !")
  :Set("admin.categories.delete.failed", "Échec de la suppression de la catégorie : {{err}}")
  :Set("admin.categories.delete.confirm", "Êtes-vous sûr de vouloir supprimer cette catégorie ?")
  
  -- Packages
  :Set("admin.packages", "Packages")
  :Set("admin.packages.create", "Créer un package")
  :Set("admin.packages.create.name", "Nom")
  :Set("admin.packages.create.name.placeholder", "Mon package")
  :Set("admin.packages.create.price", "Prix")
  :Set("admin.packages.create.currency", "Devise")
  :Set("admin.packages.create.permanent", "Est permanent ?")
  :Set("admin.packages.create.icon", "Icône")
  :Set("admin.packages.create.category", "Catégorie")
  :Set("admin.packages.create.color", "Couleur")
  :Set("admin.packages.create.next", "Suivant")
  :Set("admin.packages.create.actions", "Nouvelle action du package")
  :Set("admin.packages.create.actions.argument", "{{plural:argument|count}}")
  :Set("admin.packages.create.create", "Créer")
  :Set("admin.packages.edit", "Modifier le package")
  :Set("admin.packages.edit.edit", "Modifier")
  :Set("admin.packages.edit.delete", "Supprimer")
  :Set("admin.packages.create.success", "Package créé avec succès !")
  :Set("admin.packages.create.failed", "Échec de la création du package.")
  :Set("admin.packages.edit.success", "Package modifié avec succès !")
  :Set("admin.packages.edit.failed", "Échec de la modification du package.")
  :Set("admin.packages.delete.success", "Package supprimé avec succès !")
  :Set("admin.packages.delete.failed", "Échec de la suppression du package.")
  
  -- Packs
  :Set("admin.bundles", "Packs")
  :Set("admin.bundles.create", "Créer un pack")
  :Set("admin.bundles.create.name", "Nom")
  :Set("admin.bundles.create.name.placeholder", "Mon pack")
  :Set("admin.bundles.create.price", "Prix")
  :Set("admin.bundles.create.currency", "Devise")
  :Set("admin.bundles.create.icon", "Icône")
  :Set("admin.bundles.create.category", "Catégorie")
  :Set("admin.bundles.create.color", "Couleur")
  :Set("admin.bundles.create.next", "Suivant")
  :Set("admin.bundles.create.bundlepackage", "Nouveau package de pack")
  :Set("admin.bundles.create.create", "Créer")
  :Set("admin.bundles.edit", "Modifier le pack")
  :Set("admin.bundles.edit.edit", "Modifier")
  :Set("admin.bundles.edit.delete", "Supprimer")
  :Set("admin.bundles.create.success", "Pack créé avec succès !")
  :Set("admin.bundles.create.failed", "Échec de la création du pack.")
  :Set("admin.bundles.edit.success", "Pack modifié avec succès !")
  :Set("admin.bundles.edit.failed", "Échec de la modification du pack.")
  
  -- Remises
  :Set("percentoff", "{{percent}} % de réduction !")
  :Set("discount", "Remise")
  :Set("admin.discounts", "Remises")
  :Set("admin.discounts.delete", "Supprimer la remise")
  :Set("admin.discounts.delete.confirm", "Êtes-vous sûr de vouloir supprimer cette remise ?")
  :Set("admin.discounts.create", "Créer une remise")
  :Set("admin.discounts.create.amount", "Montant")
  :Set("admin.discounts.create.enddate", "Date de fin")
  :Set("admin.discounts.create.failed", "Échec de la création de la remise.")
  :Set("admin.discounts.create.success", "Remise créée avec succès !")
  :Set("admin.discounts.items", "Articles en promotion")
  :Set("admin.discounts.save", "Enregistrer")
  :Set("admin.discounts.items.add", "Ajouter un article")
  :Set("admin.discounts.items.add.success", "Article ajouté avec succès !")
  :Set("admin.discounts.items.add.failed", "Échec de l'ajout de l'article.")
  :Set("admin.discounts.items.remove.success", "Article supprimé avec succès !")
  :Set("admin.discounts.items.remove.failed", "Échec de la suppression de l'article.")
  
  -- Utilisateurs
  :Set("admin.users", "Utilisateurs")
  :Set("admin.users.remove", "Supprimer")
  :Set("admin.users.remove.success", "Achat supprimé avec succès !")
  :Set("admin.users.add.success", "Achat ajouté avec succès !")
  
  :Set("admin.home", "Retour à l'accueil")
  
  -- Autres
  :Set("periodic", "Vous avez reçu {{creditsCount}} {{plural:credit|creditsCount}} en récompense pour avoir joué sur le serveur !")
:Register()
