PulsarStore.Language:Language("pl", 1)
    :Plural("argument")("Argument")("Arguments")()
    :Plural("credit")("Credit")("Credits")()
    :Plural("item")("Przedmiot")("Przedmioty")()

    -- Generic
    :Set("brand", "Pulsar Store")
    :Set("admin", "Admin")
    :Set("yes", "Tak")
    :Set("no", "Nie")
    :Set("unknown", "Nieznany")
    :Set("alreadyown", "Posiadasz już ten przedmiot.")
    :Set("owned", "Posiadać")
    :Set("permanent", "Stały")
    :Set("cancel", "Anulować")
    :Set("purchase", "Zakupić")
    :Set("buy", "Kupić")
    :Set("sell", "Przedaj")
    :Set("credit", "{{plural:credit|creditsCount}}")
    :Set("credits", "Kredyt")
    :Set("money", "Pieniądze")
    :Set("close", "Zamknij")
    :Set("return", "Wróć")
    :Set("enable", "Włącz")
    :Set("enabled", "Włączone")
    :Set("disable", "Wyłącz")
    :Set("disabled", "Wyłączone")
    :Set("item", "{{plural:item|count}}")

    -- Errors
    :Set("error.permissions", "Niewystarczające uprawnienia")
    :Set("error.permissions.message", "Nie masz permisji do zrobienia tego")
    :Set("error.ratelimit", "Wysyłasz zbyt wiele żądań. Poczekaj chwile i spróbuj ponownie.")

    -- Main Menu
    :Set("mainmenu.home", "Dom")
    :Set("mainmenu.inventory", "Ekwipunek")
    :Set("mainmenu.credits.buymore", "Kup Więcej Kredytów")
    :Set("search", "Szukaj...")
    :Set("search.hidepurchased", "Ukryj Zakupione")

    -- Items
    :Set("item.discountprice", "{{oldprice}} {{newprice}} {{plural:credit|creditsCount}}")
    :Set("item.percentoff", "{{percent}}% zniżki!")
    :Set("item.whatsincluded", "Co jest wliczone?")
    :Set("item.bundle.creditstext", "{{credits}} - Pakiet")
    :Set("item.price", "{{price}} {{plural:credit|creditsCount}}")

    -- Categories
    :Set("admin.categories", "Kategorie")
    :Set("admin.categories.create", "Stwórz Kategorie")
    :Set("admin.categories.create.name", "Nazwa")
    :Set("admin.categories.create.name.placeholder", "Moja Kategoria")
    :Set("admin.categories.create.icon", "Ikona")
    :Set("admin.categories.create.color", "Kolor")
    :Set("admin.categories.create.create", "Stwórz")
    :Set("admin.categories.create.noname", "Nazwa nie może zostać pusta")
    :Set("admin.categories.create.noicon", "Ikona nie może zostać pusta")
    :Set("admin.categories.create.success", "Kategoria została utworzona pomyślnie!")
    :Set("admin.categories.create.failed", "Nie udało się utworzyć kategorii: {{err}}")
    :Set("admin.categories.edit", "Edytuj Kategorie")
    :Set("admin.categories.edit.edit", "Edytuj")
    :Set("admin.categories.edit.noname", "Nazwa nie może zostać pusta")
    :Set("admin.categories.edit.noicon", "Ikona nie może zostać pusta")
    :Set("admin.categories.edit.success", "Kategoria została edytowana pomyślnie!")
    :Set("admin.categories.edit.failed", "Nie udało się edytować kategorii: {{err}}")
    :Set("admin.categories.delete", "Usuń kategorię")
    :Set("admin.categories.delete.success", "Kategoria została pomyślnie usunięta!")
    :Set("admin.categories.delete.failed", "Nie udało się usunąć kategorii: {{err}}")
    :Set("admin.categories.delete.confirm", "Czy na pewno chcesz usunąć tę kategorię?")

    -- Packages
    :Set("admin.packages", "Pakiety")
    :Set("admin.packages.create", "Stwórz pakiet")
    :Set("admin.packages.create.name", "Nazwa")
    :Set("admin.packages.create.name.placeholder", "Moje Pakiety")
    :Set("admin.packages.create.price", "Cena")
    :Set("admin.packages.create.currency", "Waluta")
    :Set("admin.packages.create.permanent", "Czy jest trwały?")
    :Set("admin.packages.create.icon", "Ikona")
    :Set("admin.packages.create.category", "Kategoria")
    :Set("admin.packages.create.color", "Kolor")
    :Set("admin.packages.create.next", "Następny")
    :Set("admin.packages.create.actions", "Nowa Akcja Pakietu")
    :Set("admin.packages.create.actions.argument", "{{plural:argument|count}}")
    :Set("admin.packages.create.create", "Stwórz")
    :Set("admin.packages.edit", "Edytuj Pakiet")
    :Set("admin.packages.edit.edit", "Edytuj")
    :Set("admin.packages.edit.delete", "Usuń")
    :Set("admin.packages.create.success", "Pakiet został utworzony pomyślnie!")
    :Set("admin.packages.create.failed", "Wystąpił błąd podczas tworzenia pakietu.")
    :Set("admin.packages.edit.success", "Pakiet został pomyślnie edytowany!")
    :Set("admin.packages.edit.failed", "Wystąpił błąd podczas edytowania pakietu.")
    :Set("admin.packages.delete.success", "Pakiet został pomyślnie usunięty!")
    :Set("admin.packages.delete.failed", "Wystąpił błąd podczas usuwania pakietu.")

    -- Bundles
    :Set("admin.bundles", "Zestaw")
    :Set("admin.bundles.create", "Stwórz Zestaw")
    :Set("admin.bundles.create.name", "Nazwa")
    :Set("admin.bundles.create.name.placeholder", "Moje Zestawy")
    :Set("admin.bundles.create.price", "Cena")
    :Set("admin.bundles.create.currency", "Waluta")
    :Set("admin.bundles.create.icon", "Ikona")
    :Set("admin.bundles.create.category", "Kategoria")
    :Set("admin.bundles.create.color", "Kolor")
    :Set("admin.bundles.create.next", "Następny")
    :Set("admin.bundles.create.bundlepackage", "Nowy Zestaw")
    :Set("admin.bundles.create.create", "Stwórz")
    :Set("admin.bundles.edit", "Edytuj Zestaw")
    :Set("admin.bundles.edit.edit", "Edytuj")
    :Set("admin.bundles.edit.delete", "Usuń")
    :Set("admin.bundles.create.success", "Zestaw utworzony pomyślnie!")
    :Set("admin.bundles.create.failed", "Wystąpił błąd podczas tworzenia zestawu...")
    :Set("admin.bundles.edit.success", "Zestaw edytowany pomyślnie")
    :Set("admin.bundles.edit.failed", "Wystąpił błąd podczas edytowania zestawu...")

    -- Discounts
    :Set("percentoff", "{{percent}}% zniżki!")
    :Set("discount", "Rabat")
    :Set("admin.discounts", "Rabaty")
    :Set("admin.discounts.delete", "Usuń Rabat")
    :Set("admin.discounts.delete.confirm", "Czy na pewno chcesz usunąć tę zniżkę?")
    :Set("admin.discounts.create", "Stwórz Rabat")
    :Set("admin.discounts.create.amount", "Ilość")
    :Set("admin.discounts.create.enddate", "Data końcowa")
    :Set("admin.discounts.create.failed", "Wystąpił błąd poczas tworzenia zniżki.")
    :Set("admin.discounts.create.success", "Zniżka stworzona pomyślnie")
    :Set("admin.discounts.items", "Przedmioty objęte rabatem")
    :Set("admin.discounts.save", "Zapisz")
    :Set("admin.discounts.items.add", "Dodaj przedmiot")
    :Set("admin.discounts.items.add.success", "Przedmiot został dodany domyślnie!")
    :Set("admin.discounts.items.add.failed", "Wystąpił błąd podczas tworzenia przedmiotu...")
    :Set("admin.discounts.items.remove.success", "Przedmiot usunięty pomyślnie!")
    :Set("admin.discounts.items.remove.failed", "Wystąpił błąd podczas usuwania przedmiotu...")

    -- Users
    :Set("admin.users", "Użytkownicy")
    :Set("admin.users.remove", "Usuń")
    :Set("admin.users.remove.success", "Pomyślnie usunięto zakup!")
    :Set("admin.users.add.success", "Pomyślnie zakup został dodany!")

    :Set("admin.home", "Wróć do domu")

    -- Other
    :Set("periodic", "Zostałeś nagrodzony {{creditsCount}} {{plural:credit|creditsCount}} za grę na tym serwerze!")
:Register()